/** @type {import('tailwindcss').Config} */
module.exports = {
    content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
    presets: [require("nativewind/preset")],
    theme: {
        extend: {
            colors: {
                divvit: {
                    dark: '#FFFFFF',
                    card: '#FFFFFF',
                    primary: '#6346cd',
                    secondary: '#6346cd',
                    text: '#111827',
                    muted: '#484554',
                    'stat-bg': '#f1f3ff',
                    'input-bg': '#FFFFFF',
                    'input-border': '#e5e7eb',
                },
                "surface": "#f9f9ff",
                "on-surface": "#111827",
                "on-surface-variant": "#484554",
                "surface-container-low": "#f1f3ff",
                "surface-container-highest": "#e5e7eb",
                "surface-container": "#f1f3ff",
                "surface-container-lowest": "#ffffff",
                "primary": "#6346cd",
                "on-primary": "#ffffff",
                "primary-container": "#4b29b4",
                "error": "#dc2626",
                "on-primary-fixed-variant": "#4b29b4",
                "surface-container-high": "#f1f3ff",
                "background": "#f9f9ff",
                "on-background": "#111827",
                "primary-fixed": "#f1f3ff",
                "secondary-fixed": "#f1f3ff",
                "secondary-fixed-dim": "#e5e7eb",
                "on-secondary-fixed-variant": "#484554",
                "on-secondary-fixed": "#111827",
                "secondary": "#484554",
                "on-secondary": "#ffffff",
                "secondary-container": "#e5e7eb",
                "on-secondary-container": "#484554",
                "inverse-surface": "#111827",
                "inverse-primary": "#f1f3ff",
                "surface-tint": "#6346cd",
                "on-primary-container": "#f1f3ff",
                "surface-variant": "#e5e7eb",
                "surface-dim": "#e5e7eb",
                "surface-bright": "#f9f9ff",
                "inverse-on-surface": "#f9f9ff",
                "outline": "#9ca3af",
                "outline-variant": "#e5e7eb",
                "on-error": "#ffffff",
                "error-container": "#fee2e2",
            },
            fontFamily: {
                heading: ['Outfit_700Bold'],
                body: ['Outfit_400Regular'],
                medium: ['Outfit_500Medium'],
            }
        },
    },
    plugins: [],
}
