/** @type {import('tailwindcss').Config} */
module.exports = {
    content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
    presets: [require("nativewind/preset")],
    theme: {
        extend: {
            colors: {
                divvit: {
                    dark: '#FFFFFF',
                    card: '#FFFFFF',
                    primary: '#6346cd',
                    secondary: '#6346cd',
                    text: '#111827',
                    muted: '#484554',
                    'stat-bg': '#f1f3ff',
                    'input-bg': '#FFFFFF',
                    'input-border': '#e5e7eb',
                },
                primary: '#6346cd',
                'primary-dim': '#5328d0',
                'primary-container': '#a590ff',
                'primary-fixed': '#a590ff',
                'primary-fixed-dim': '#9880ff',
                'on-primary': '#f6f0ff',
                'on-primary-container': '#250074',
                'on-primary-fixed': '#000000',
                'on-primary-fixed-variant': '#2e008d',
                secondary: '#6e45ac',
                'secondary-dim': '#61389f',
                'secondary-container': '#dfc8ff',
                'secondary-fixed': '#dfc8ff',
                'secondary-fixed-dim': '#d4b7ff',
                'on-secondary': '#f9efff',
                'on-secondary-container': '#592f96',
                'on-secondary-fixed': '#451682',
                'on-secondary-fixed-variant': '#6339a0',
                tertiary: '#9b3664',
                'tertiary-dim': '#8c2958',
                'tertiary-container': '#ff8cba',
                'tertiary-fixed': '#ff8cba',
                'tertiary-fixed-dim': '#f37cad',
                'on-tertiary': '#ffeff2',
                'on-tertiary-container': '#630338',
                'on-tertiary-fixed': '#37001c',
                'on-tertiary-fixed-variant': '#6f1041',
                error: '#b41340',
                'error-dim': '#a70138',
                'error-container': '#f74b6d',
                'on-error': '#ffefef',
                'on-error-container': '#510017',
                background: '#fcf4ff',
                surface: '#fcf4ff',
                'surface-bright': '#fcf4ff',
                'surface-dim': '#e1cbff',
                'surface-tint': '#6346cd',
                'surface-variant': '#e8d5ff',
                'surface-container-lowest': '#ffffff',
                'surface-container-low': '#f8edff',
                'surface-container': '#f1e3ff',
                'surface-container-high': '#ecdcff',
                'surface-container-highest': '#e8d5ff',
                'on-background': '#36274d',
                'on-surface': '#36274d',
                'on-surface-variant': '#64547d',
                outline: '#806f9a',
                'outline-variant': '#b8a5d3',
                'inverse-surface': '#14052b',
                'inverse-on-surface': '#a895c2',
                'inverse-primary': '#967cff',
            },
            borderRadius: {
                DEFAULT: '16px',
                lg: '32px',
                xl: '48px',
                full: '9999px',
            },
            fontFamily: {
                heading: ['Outfit_700Bold'],
                medium: ['Outfit_500Medium'],
                headline: ['Manrope'],
                display: ['Manrope'],
                body: ['Manrope'],
                label: ['Manrope'],
                outfit: ['Outfit']
            }
        },
    },
    plugins: [],
}
